-- Famous OSS schemas as text2sql targets. Auto-generated by gen_oss_testenv.py.

CREATE SCHEMA IF NOT EXISTS sakila;
CREATE TABLE IF NOT EXISTS sakila.category (
	category_id INT,
	name TEXT,
	PRIMARY KEY (category_id)
);
CREATE TABLE IF NOT EXISTS sakila.actor (
	actor_id INT,
	first_name TEXT,
	last_name TEXT,
	PRIMARY KEY (actor_id)
);
CREATE TABLE IF NOT EXISTS sakila.film (
	film_id INT,
	title TEXT,
	release_year INT,
	rental_duration INT,
	rental_rate INT,
	length INT,
	rating TEXT,
	PRIMARY KEY (film_id)
);
CREATE TABLE IF NOT EXISTS sakila.film_category (
	film_id INT,
	category_id INT,
	PRIMARY KEY (film_id, category_id)
);
CREATE TABLE IF NOT EXISTS sakila.film_actor (
	actor_id INT,
	film_id INT,
	PRIMARY KEY (actor_id, film_id)
);
CREATE TABLE IF NOT EXISTS sakila.inventory (
	inventory_id INT,
	film_id INT,
	store_id INT,
	PRIMARY KEY (inventory_id)
);
CREATE TABLE IF NOT EXISTS sakila.customer (
	customer_id INT,
	first_name TEXT,
	last_name TEXT,
	email TEXT,
	active BOOLEAN,
	create_date TIMESTAMPTZ,
	PRIMARY KEY (customer_id)
);
CREATE TABLE IF NOT EXISTS sakila.rental (
	rental_id INT,
	rental_date TIMESTAMPTZ,
	inventory_id INT,
	customer_id INT,
	return_date TIMESTAMPTZ,
	PRIMARY KEY (rental_id)
);
CREATE TABLE IF NOT EXISTS sakila.payment (
	payment_id INT,
	customer_id INT,
	rental_id INT,
	amount INT,
	payment_date TIMESTAMPTZ,
	PRIMARY KEY (payment_id)
);
INSERT INTO sakila.category (category_id, name) VALUES (1, 'Action');
INSERT INTO sakila.category (category_id, name) VALUES (2, 'Comedy');
INSERT INTO sakila.category (category_id, name) VALUES (3, 'Drama');
INSERT INTO sakila.category (category_id, name) VALUES (4, 'Horror');
INSERT INTO sakila.category (category_id, name) VALUES (5, 'Sci-Fi');
INSERT INTO sakila.category (category_id, name) VALUES (6, 'Documentary');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (1, 'PENELOPE', 'GUINESS');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (2, 'NICK', 'WAHLBERG');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (3, 'ED', 'CHASE');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (4, 'JENNIFER', 'DAVIS');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (5, 'JOHNNY', 'LOLLOBRIGIDA');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (6, 'BETTE', 'NICHOLSON');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (7, 'GRACE', 'MOSTEL');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (8, 'MATTHEW', 'JOHANSSON');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (9, 'JOE', 'SWANK');
INSERT INTO sakila.actor (actor_id, first_name, last_name) VALUES (10, 'CHRISTIAN', 'GABLE');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (1, 'FILM TITLE 01', 2019, 4, 199, 83, 'PG');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (2, 'FILM TITLE 02', 2020, 5, 299, 86, 'PG-13');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (3, 'FILM TITLE 03', 2021, 6, 99, 89, 'R');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (4, 'FILM TITLE 04', 2022, 7, 199, 92, 'G');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (5, 'FILM TITLE 05', 2023, 3, 299, 95, 'PG');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (6, 'FILM TITLE 06', 2018, 4, 99, 98, 'PG-13');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (7, 'FILM TITLE 07', 2019, 5, 199, 101, 'R');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (8, 'FILM TITLE 08', 2020, 6, 299, 104, 'G');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (9, 'FILM TITLE 09', 2021, 7, 99, 107, 'PG');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (10, 'FILM TITLE 10', 2022, 3, 199, 110, 'PG-13');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (11, 'FILM TITLE 11', 2023, 4, 299, 113, 'R');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (12, 'FILM TITLE 12', 2018, 5, 99, 116, 'G');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (13, 'FILM TITLE 13', 2019, 6, 199, 119, 'PG');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (14, 'FILM TITLE 14', 2020, 7, 299, 122, 'PG-13');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (15, 'FILM TITLE 15', 2021, 3, 99, 125, 'R');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (16, 'FILM TITLE 16', 2022, 4, 199, 128, 'G');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (17, 'FILM TITLE 17', 2023, 5, 299, 131, 'PG');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (18, 'FILM TITLE 18', 2018, 6, 99, 134, 'PG-13');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (19, 'FILM TITLE 19', 2019, 7, 199, 137, 'R');
INSERT INTO sakila.film (film_id, title, release_year, rental_duration, rental_rate, length, rating) VALUES (20, 'FILM TITLE 20', 2020, 3, 299, 140, 'G');
INSERT INTO sakila.film_category (film_id, category_id) VALUES (1, 2);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (2, 3);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (3, 4);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (4, 5);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (5, 6);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (6, 1);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (7, 2);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (8, 3);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (9, 4);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (10, 5);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (11, 6);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (12, 1);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (13, 2);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (14, 3);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (15, 4);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (16, 5);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (17, 6);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (18, 1);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (19, 2);
INSERT INTO sakila.film_category (film_id, category_id) VALUES (20, 3);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (1, 7);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (1, 10);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (1, 17);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (1, 20);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (2, 1);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (2, 8);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (2, 11);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (2, 18);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (3, 2);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (3, 9);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (3, 12);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (3, 19);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (4, 3);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (4, 10);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (4, 13);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (4, 20);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (5, 1);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (5, 2);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (5, 4);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (5, 6);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (5, 11);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (5, 14);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (6, 2);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (6, 5);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (6, 12);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (6, 15);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (7, 3);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (7, 6);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (7, 13);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (7, 16);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (8, 4);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (8, 7);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (8, 14);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (8, 17);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (9, 5);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (9, 8);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (9, 15);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (9, 18);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (10, 6);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (10, 9);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (10, 16);
INSERT INTO sakila.film_actor (actor_id, film_id) VALUES (10, 19);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (1, 1, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (2, 1, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (3, 2, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (4, 3, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (5, 3, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (6, 4, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (7, 5, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (8, 5, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (9, 6, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (10, 7, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (11, 7, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (12, 8, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (13, 9, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (14, 9, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (15, 10, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (16, 11, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (17, 11, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (18, 12, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (19, 13, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (20, 13, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (21, 14, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (22, 15, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (23, 15, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (24, 16, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (25, 17, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (26, 17, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (27, 18, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (28, 19, 1);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (29, 19, 2);
INSERT INTO sakila.inventory (inventory_id, film_id, store_id) VALUES (30, 20, 1);
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (1, 'MARY', 'CUST01', 'cust01@sakila.example.com', TRUE, '2026-01-01 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (2, 'PATRICIA', 'CUST02', 'cust02@sakila.example.com', TRUE, '2026-01-02 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (3, 'LINDA', 'CUST03', 'cust03@sakila.example.com', TRUE, '2026-01-03 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (4, 'BARBARA', 'CUST04', 'cust04@sakila.example.com', TRUE, '2026-01-04 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (5, 'ELIZABETH', 'CUST05', 'cust05@sakila.example.com', TRUE, '2026-01-05 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (6, 'JENNIFER', 'CUST06', 'cust06@sakila.example.com', TRUE, '2026-01-06 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (7, 'MARIA', 'CUST07', 'cust07@sakila.example.com', TRUE, '2026-01-07 10:00:00');
INSERT INTO sakila.customer (customer_id, first_name, last_name, email, active, create_date) VALUES (8, 'SUSAN', 'CUST08', 'cust08@sakila.example.com', FALSE, '2026-01-08 10:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (1, '2026-06-01 09:00:00', 2, 2, '2026-06-03 09:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (2, '2026-06-01 10:00:00', 3, 3, '2026-06-03 10:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (3, '2026-06-01 11:00:00', 4, 4, '2026-06-03 11:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (4, '2026-06-01 12:00:00', 5, 5, '2026-06-03 12:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (5, '2026-06-01 13:00:00', 6, 6, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (6, '2026-06-01 14:00:00', 7, 7, '2026-06-03 14:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (7, '2026-06-01 15:00:00', 8, 8, '2026-06-03 15:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (8, '2026-06-02 16:00:00', 9, 1, '2026-06-04 16:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (9, '2026-06-02 17:00:00', 10, 2, '2026-06-04 17:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (10, '2026-06-02 18:00:00', 11, 3, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (11, '2026-06-02 19:00:00', 12, 4, '2026-06-04 19:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (12, '2026-06-02 08:00:00', 13, 5, '2026-06-04 08:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (13, '2026-06-02 09:00:00', 14, 6, '2026-06-04 09:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (14, '2026-06-02 10:00:00', 15, 7, '2026-06-04 10:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (15, '2026-06-02 11:00:00', 16, 8, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (16, '2026-06-03 12:00:00', 17, 1, '2026-06-05 12:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (17, '2026-06-03 13:00:00', 18, 2, '2026-06-05 13:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (18, '2026-06-03 14:00:00', 19, 3, '2026-06-05 14:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (19, '2026-06-03 15:00:00', 20, 4, '2026-06-05 15:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (20, '2026-06-03 16:00:00', 21, 5, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (21, '2026-06-03 17:00:00', 22, 6, '2026-06-05 17:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (22, '2026-06-03 18:00:00', 23, 7, '2026-06-05 18:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (23, '2026-06-03 19:00:00', 24, 8, '2026-06-05 19:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (24, '2026-06-04 08:00:00', 25, 1, '2026-06-06 08:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (25, '2026-06-04 09:00:00', 26, 2, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (26, '2026-06-04 10:00:00', 27, 3, '2026-06-06 10:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (27, '2026-06-04 11:00:00', 28, 4, '2026-06-06 11:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (28, '2026-06-04 12:00:00', 29, 5, '2026-06-06 12:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (29, '2026-06-04 13:00:00', 30, 6, '2026-06-06 13:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (30, '2026-06-04 14:00:00', 1, 7, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (31, '2026-06-04 15:00:00', 2, 8, '2026-06-06 15:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (32, '2026-06-05 16:00:00', 3, 1, '2026-06-07 16:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (33, '2026-06-05 17:00:00', 4, 2, '2026-06-07 17:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (34, '2026-06-05 18:00:00', 5, 3, '2026-06-07 18:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (35, '2026-06-05 19:00:00', 6, 4, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (36, '2026-06-05 08:00:00', 7, 5, '2026-06-07 08:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (37, '2026-06-05 09:00:00', 8, 6, '2026-06-07 09:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (38, '2026-06-05 10:00:00', 9, 7, '2026-06-07 10:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (39, '2026-06-05 11:00:00', 10, 8, '2026-06-07 11:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (40, '2026-06-06 12:00:00', 11, 1, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (41, '2026-06-06 13:00:00', 12, 2, '2026-06-08 13:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (42, '2026-06-06 14:00:00', 13, 3, '2026-06-08 14:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (43, '2026-06-06 15:00:00', 14, 4, '2026-06-08 15:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (44, '2026-06-06 16:00:00', 15, 5, '2026-06-08 16:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (45, '2026-06-06 17:00:00', 16, 6, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (46, '2026-06-06 18:00:00', 17, 7, '2026-06-08 18:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (47, '2026-06-06 19:00:00', 18, 8, '2026-06-08 19:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (48, '2026-06-07 08:00:00', 19, 1, '2026-06-09 08:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (49, '2026-06-07 09:00:00', 20, 2, '2026-06-09 09:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (50, '2026-06-07 10:00:00', 21, 3, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (51, '2026-06-07 11:00:00', 22, 4, '2026-06-09 11:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (52, '2026-06-07 12:00:00', 23, 5, '2026-06-09 12:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (53, '2026-06-07 13:00:00', 24, 6, '2026-06-09 13:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (54, '2026-06-07 14:00:00', 25, 7, '2026-06-09 14:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (55, '2026-06-07 15:00:00', 26, 8, NULL);
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (56, '2026-06-08 16:00:00', 27, 1, '2026-06-10 16:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (57, '2026-06-08 17:00:00', 28, 2, '2026-06-10 17:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (58, '2026-06-08 18:00:00', 29, 3, '2026-06-10 18:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (59, '2026-06-08 19:00:00', 30, 4, '2026-06-10 19:00:00');
INSERT INTO sakila.rental (rental_id, rental_date, inventory_id, customer_id, return_date) VALUES (60, '2026-06-08 08:00:00', 1, 5, NULL);
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (1, 2, 1, 299, '2026-06-01 09:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (2, 3, 2, 399, '2026-06-01 10:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (3, 4, 3, 499, '2026-06-01 11:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (4, 5, 4, 199, '2026-06-01 12:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (5, 6, 5, 299, '2026-06-01 13:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (6, 7, 6, 399, '2026-06-01 14:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (7, 8, 7, 499, '2026-06-01 15:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (8, 1, 8, 199, '2026-06-02 16:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (9, 2, 9, 299, '2026-06-02 17:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (10, 3, 10, 399, '2026-06-02 18:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (11, 4, 11, 499, '2026-06-02 19:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (12, 5, 12, 199, '2026-06-02 08:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (13, 6, 13, 299, '2026-06-02 09:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (14, 7, 14, 399, '2026-06-02 10:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (15, 8, 15, 499, '2026-06-02 11:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (16, 1, 16, 199, '2026-06-03 12:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (17, 2, 17, 299, '2026-06-03 13:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (18, 3, 18, 399, '2026-06-03 14:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (19, 4, 19, 499, '2026-06-03 15:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (20, 5, 20, 199, '2026-06-03 16:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (21, 6, 21, 299, '2026-06-03 17:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (22, 7, 22, 399, '2026-06-03 18:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (23, 8, 23, 499, '2026-06-03 19:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (24, 1, 24, 199, '2026-06-04 08:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (25, 2, 25, 299, '2026-06-04 09:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (26, 3, 26, 399, '2026-06-04 10:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (27, 4, 27, 499, '2026-06-04 11:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (28, 5, 28, 199, '2026-06-04 12:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (29, 6, 29, 299, '2026-06-04 13:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (30, 7, 30, 399, '2026-06-04 14:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (31, 8, 31, 499, '2026-06-04 15:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (32, 1, 32, 199, '2026-06-05 16:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (33, 2, 33, 299, '2026-06-05 17:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (34, 3, 34, 399, '2026-06-05 18:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (35, 4, 35, 499, '2026-06-05 19:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (36, 5, 36, 199, '2026-06-05 08:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (37, 6, 37, 299, '2026-06-05 09:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (38, 7, 38, 399, '2026-06-05 10:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (39, 8, 39, 499, '2026-06-05 11:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (40, 1, 40, 199, '2026-06-06 12:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (41, 2, 41, 299, '2026-06-06 13:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (42, 3, 42, 399, '2026-06-06 14:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (43, 4, 43, 499, '2026-06-06 15:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (44, 5, 44, 199, '2026-06-06 16:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (45, 6, 45, 299, '2026-06-06 17:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (46, 7, 46, 399, '2026-06-06 18:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (47, 8, 47, 499, '2026-06-06 19:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (48, 1, 48, 199, '2026-06-07 08:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (49, 2, 49, 299, '2026-06-07 09:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (50, 3, 50, 399, '2026-06-07 10:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (51, 4, 51, 499, '2026-06-07 11:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (52, 5, 52, 199, '2026-06-07 12:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (53, 6, 53, 299, '2026-06-07 13:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (54, 7, 54, 399, '2026-06-07 14:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (55, 8, 55, 499, '2026-06-07 15:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (56, 1, 56, 199, '2026-06-08 16:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (57, 2, 57, 299, '2026-06-08 17:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (58, 3, 58, 399, '2026-06-08 18:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (59, 4, 59, 499, '2026-06-08 19:00:00');
INSERT INTO sakila.payment (payment_id, customer_id, rental_id, amount, payment_date) VALUES (60, 5, 60, 199, '2026-06-08 08:00:00');
GRANT USAGE ON SCHEMA sakila TO jamypg_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA sakila TO jamypg_ro;

CREATE SCHEMA IF NOT EXISTS northwind;
CREATE TABLE IF NOT EXISTS northwind.categories (
	category_id INT,
	category_name TEXT,
	description TEXT,
	PRIMARY KEY (category_id)
);
CREATE TABLE IF NOT EXISTS northwind.suppliers (
	supplier_id INT,
	company_name TEXT,
	country TEXT,
	PRIMARY KEY (supplier_id)
);
CREATE TABLE IF NOT EXISTS northwind.products (
	product_id INT,
	product_name TEXT,
	supplier_id INT,
	category_id INT,
	unit_price INT,
	units_in_stock INT,
	discontinued BOOLEAN,
	PRIMARY KEY (product_id)
);
CREATE TABLE IF NOT EXISTS northwind.customers (
	customer_id TEXT,
	company_name TEXT,
	country TEXT,
	city TEXT,
	PRIMARY KEY (customer_id)
);
CREATE TABLE IF NOT EXISTS northwind.employees (
	employee_id INT,
	last_name TEXT,
	first_name TEXT,
	title TEXT,
	hire_date TIMESTAMPTZ,
	PRIMARY KEY (employee_id)
);
CREATE TABLE IF NOT EXISTS northwind.shippers (
	shipper_id INT,
	company_name TEXT,
	PRIMARY KEY (shipper_id)
);
CREATE TABLE IF NOT EXISTS northwind.orders (
	order_id INT,
	customer_id TEXT,
	employee_id INT,
	order_date TIMESTAMPTZ,
	shipped_date TIMESTAMPTZ,
	ship_via INT,
	freight INT,
	ship_country TEXT,
	PRIMARY KEY (order_id)
);
CREATE TABLE IF NOT EXISTS northwind.order_details (
	order_id INT,
	product_id INT,
	unit_price INT,
	quantity INT,
	discount_pct INT,
	PRIMARY KEY (order_id, product_id)
);
INSERT INTO northwind.categories (category_id, category_name, description) VALUES (1, 'Beverages', 'Beverages products');
INSERT INTO northwind.categories (category_id, category_name, description) VALUES (2, 'Condiments', 'Condiments products');
INSERT INTO northwind.categories (category_id, category_name, description) VALUES (3, 'Confections', 'Confections products');
INSERT INTO northwind.categories (category_id, category_name, description) VALUES (4, 'Dairy', 'Dairy products');
INSERT INTO northwind.categories (category_id, category_name, description) VALUES (5, 'Seafood', 'Seafood products');
INSERT INTO northwind.suppliers (supplier_id, company_name, country) VALUES (1, 'Supplier A', 'USA');
INSERT INTO northwind.suppliers (supplier_id, company_name, country) VALUES (2, 'Supplier B', 'UK');
INSERT INTO northwind.suppliers (supplier_id, company_name, country) VALUES (3, 'Supplier C', 'Japan');
INSERT INTO northwind.suppliers (supplier_id, company_name, country) VALUES (4, 'Supplier D', 'Germany');
INSERT INTO northwind.suppliers (supplier_id, company_name, country) VALUES (5, 'Supplier E', 'Korea');
INSERT INTO northwind.suppliers (supplier_id, company_name, country) VALUES (6, 'Supplier F', 'France');
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (1, 'Product 01', 2, 2, 650, 17, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (2, 'Product 02', 3, 3, 800, 24, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (3, 'Product 03', 4, 4, 950, 31, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (4, 'Product 04', 5, 5, 1100, 38, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (5, 'Product 05', 6, 1, 1250, 45, TRUE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (6, 'Product 06', 1, 2, 1400, 52, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (7, 'Product 07', 2, 3, 1550, 59, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (8, 'Product 08', 3, 4, 1700, 66, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (9, 'Product 09', 4, 5, 1850, 73, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (10, 'Product 10', 5, 1, 2000, 80, TRUE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (11, 'Product 11', 6, 2, 2150, 87, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (12, 'Product 12', 1, 3, 2300, 94, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (13, 'Product 13', 2, 4, 2450, 11, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (14, 'Product 14', 3, 5, 2600, 18, FALSE);
INSERT INTO northwind.products (product_id, product_name, supplier_id, category_id, unit_price, units_in_stock, discontinued) VALUES (15, 'Product 15', 4, 1, 2750, 25, TRUE);
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST1', 'Customer Co 1', 'Korea', 'City1');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST2', 'Customer Co 2', 'USA', 'City2');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST3', 'Customer Co 3', 'UK', 'City3');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST4', 'Customer Co 4', 'Japan', 'City4');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST5', 'Customer Co 5', 'Germany', 'City5');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST6', 'Customer Co 6', 'France', 'City6');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST7', 'Customer Co 7', 'Canada', 'City7');
INSERT INTO northwind.customers (customer_id, company_name, country, city) VALUES ('CUST8', 'Customer Co 8', 'Spain', 'City8');
INSERT INTO northwind.employees (employee_id, last_name, first_name, title, hire_date) VALUES (1, 'Davolio', 'Nancy', 'Sales Representative', '2024-01-15 09:00:00');
INSERT INTO northwind.employees (employee_id, last_name, first_name, title, hire_date) VALUES (2, 'Fuller', 'Andrew', 'Vice President', '2024-02-15 09:00:00');
INSERT INTO northwind.employees (employee_id, last_name, first_name, title, hire_date) VALUES (3, 'Leverling', 'Janet', 'Sales Representative', '2024-03-15 09:00:00');
INSERT INTO northwind.employees (employee_id, last_name, first_name, title, hire_date) VALUES (4, 'Peacock', 'Margaret', 'Sales Representative', '2024-04-15 09:00:00');
INSERT INTO northwind.employees (employee_id, last_name, first_name, title, hire_date) VALUES (5, 'Buchanan', 'Steven', 'Sales Manager', '2024-05-15 09:00:00');
INSERT INTO northwind.shippers (shipper_id, company_name) VALUES (1, 'Speedy Express');
INSERT INTO northwind.shippers (shipper_id, company_name) VALUES (2, 'United Package');
INSERT INTO northwind.shippers (shipper_id, company_name) VALUES (3, 'Federal Shipping');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10248, 'CUST2', 2, '2026-06-02 00:00:00', '2026-06-05 00:00:00', 2, 320, 'USA');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10249, 'CUST3', 3, '2026-06-03 00:00:00', '2026-06-06 00:00:00', 3, 340, 'UK');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10250, 'CUST4', 4, '2026-06-04 00:00:00', '2026-06-07 00:00:00', 1, 360, 'Japan');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10251, 'CUST5', 5, '2026-06-05 00:00:00', '2026-06-08 00:00:00', 2, 380, 'Germany');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10252, 'CUST6', 1, '2026-06-06 00:00:00', '2026-06-09 00:00:00', 3, 400, 'France');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10253, 'CUST7', 2, '2026-06-07 00:00:00', NULL, 1, 420, 'Canada');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10254, 'CUST8', 3, '2026-06-08 00:00:00', '2026-06-11 00:00:00', 2, 440, 'Spain');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10255, 'CUST1', 4, '2026-06-09 00:00:00', '2026-06-12 00:00:00', 3, 460, 'Korea');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10256, 'CUST2', 5, '2026-06-10 00:00:00', '2026-06-13 00:00:00', 1, 480, 'USA');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10257, 'CUST3', 1, '2026-06-11 00:00:00', '2026-06-14 00:00:00', 2, 500, 'UK');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10258, 'CUST4', 2, '2026-06-12 00:00:00', '2026-06-15 00:00:00', 3, 520, 'Japan');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10259, 'CUST5', 3, '2026-06-13 00:00:00', NULL, 1, 540, 'Germany');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10260, 'CUST6', 4, '2026-06-14 00:00:00', '2026-06-17 00:00:00', 2, 560, 'France');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10261, 'CUST7', 5, '2026-06-15 00:00:00', '2026-06-18 00:00:00', 3, 580, 'Canada');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10262, 'CUST8', 1, '2026-06-16 00:00:00', '2026-06-19 00:00:00', 1, 600, 'Spain');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10263, 'CUST1', 2, '2026-06-17 00:00:00', '2026-06-20 00:00:00', 2, 620, 'Korea');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10264, 'CUST2', 3, '2026-06-18 00:00:00', '2026-06-21 00:00:00', 3, 640, 'USA');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10265, 'CUST3', 4, '2026-06-19 00:00:00', NULL, 1, 660, 'UK');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10266, 'CUST4', 5, '2026-06-20 00:00:00', '2026-06-23 00:00:00', 2, 680, 'Japan');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10267, 'CUST5', 1, '2026-06-21 00:00:00', '2026-06-24 00:00:00', 3, 700, 'Germany');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10268, 'CUST6', 2, '2026-06-22 00:00:00', '2026-06-25 00:00:00', 1, 720, 'France');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10269, 'CUST7', 3, '2026-06-23 00:00:00', '2026-06-26 00:00:00', 2, 740, 'Canada');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10270, 'CUST8', 4, '2026-06-24 00:00:00', '2026-06-27 00:00:00', 3, 760, 'Spain');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10271, 'CUST1', 5, '2026-06-25 00:00:00', NULL, 1, 780, 'Korea');
INSERT INTO northwind.orders (order_id, customer_id, employee_id, order_date, shipped_date, ship_via, freight, ship_country) VALUES (10272, 'CUST2', 1, '2026-06-26 00:00:00', '2026-06-28 00:00:00', 2, 800, 'USA');
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10248, 9, 1850, 2, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10248, 2, 800, 2, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10249, 10, 2000, 3, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10249, 3, 950, 3, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10250, 11, 2150, 4, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10250, 4, 1100, 4, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10251, 12, 2300, 5, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10251, 5, 1250, 5, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10252, 13, 2450, 1, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10252, 6, 1400, 1, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10253, 14, 2600, 2, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10253, 7, 1550, 2, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10254, 8, 1700, 3, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10254, 15, 2750, 3, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10255, 9, 1850, 4, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10255, 1, 650, 4, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10256, 10, 2000, 5, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10256, 2, 800, 5, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10257, 3, 950, 1, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10257, 11, 2150, 1, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10258, 12, 2300, 2, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10258, 4, 1100, 2, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10259, 5, 1250, 3, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10259, 13, 2450, 3, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10260, 14, 2600, 4, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10260, 6, 1400, 4, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10261, 7, 1550, 5, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10261, 15, 2750, 5, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10262, 8, 1700, 1, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10262, 1, 650, 1, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10263, 9, 1850, 2, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10263, 2, 800, 2, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10264, 10, 2000, 3, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10264, 3, 950, 3, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10265, 11, 2150, 4, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10265, 4, 1100, 4, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10266, 12, 2300, 5, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10266, 5, 1250, 5, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10267, 13, 2450, 1, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10267, 6, 1400, 1, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10268, 14, 2600, 2, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10268, 7, 1550, 2, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10269, 8, 1700, 3, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10269, 15, 2750, 3, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10270, 9, 1850, 4, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10270, 1, 650, 4, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10271, 10, 2000, 5, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10271, 2, 800, 5, 10);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10272, 3, 950, 1, 0);
INSERT INTO northwind.order_details (order_id, product_id, unit_price, quantity, discount_pct) VALUES (10272, 11, 2150, 1, 0);
GRANT USAGE ON SCHEMA northwind TO jamypg_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA northwind TO jamypg_ro;

CREATE SCHEMA IF NOT EXISTS wordpress;
CREATE TABLE IF NOT EXISTS wordpress.wp_users (
	id INT,
	user_login TEXT,
	user_email TEXT,
	display_name TEXT,
	user_registered TIMESTAMPTZ,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_posts (
	id INT,
	post_author INT,
	post_date TIMESTAMPTZ,
	post_title TEXT,
	post_status TEXT,
	post_type TEXT,
	comment_count INT,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_comments (
	comment_id INT,
	comment_post_id INT,
	comment_author TEXT,
	comment_date TIMESTAMPTZ,
	comment_approved TEXT,
	PRIMARY KEY (comment_id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_terms (
	term_id INT,
	name TEXT,
	slug TEXT,
	PRIMARY KEY (term_id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_term_taxonomy (
	term_taxonomy_id INT,
	term_id INT,
	taxonomy TEXT,
	PRIMARY KEY (term_taxonomy_id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_term_relationships (
	object_id INT,
	term_taxonomy_id INT,
	PRIMARY KEY (object_id, term_taxonomy_id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_postmeta (
	meta_id INT,
	post_id INT,
	meta_key TEXT,
	meta_value TEXT,
	PRIMARY KEY (meta_id)
);
CREATE TABLE IF NOT EXISTS wordpress.wp_options (
	option_id INT,
	option_name TEXT,
	option_value TEXT,
	PRIMARY KEY (option_id)
);
INSERT INTO wordpress.wp_users (id, user_login, user_email, display_name, user_registered) VALUES (1, 'admin', 'admin@blog.example.com', '관리자', '2025-01-01 09:00:00');
INSERT INTO wordpress.wp_users (id, user_login, user_email, display_name, user_registered) VALUES (2, 'alice', 'alice@blog.example.com', 'Alice Kim', '2025-02-01 09:00:00');
INSERT INTO wordpress.wp_users (id, user_login, user_email, display_name, user_registered) VALUES (3, 'bob', 'bob@blog.example.com', 'Bob Lee', '2025-03-01 09:00:00');
INSERT INTO wordpress.wp_users (id, user_login, user_email, display_name, user_registered) VALUES (4, 'carol', 'carol@blog.example.com', 'Carol Park', '2025-04-01 09:00:00');
INSERT INTO wordpress.wp_users (id, user_login, user_email, display_name, user_registered) VALUES (5, 'dave', 'dave@blog.example.com', 'Dave Choi', '2025-05-01 09:00:00');
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (1, 2, '2026-05-02 12:00:00', 'Post Title 01', 'publish', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (2, 3, '2026-05-03 12:00:00', 'Post Title 02', 'publish', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (3, 4, '2026-05-04 12:00:00', 'Post Title 03', 'draft', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (4, 5, '2026-05-05 12:00:00', 'Post Title 04', 'publish', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (5, 2, '2026-05-06 12:00:00', 'Post Title 05', 'publish', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (6, 2, '2026-05-07 12:00:00', 'Post Title 06', 'draft', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (7, 3, '2026-05-08 12:00:00', 'Post Title 07', 'publish', 'page', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (8, 4, '2026-05-09 12:00:00', 'Post Title 08', 'publish', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (9, 5, '2026-05-10 12:00:00', 'Post Title 09', 'draft', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (10, 2, '2026-05-11 12:00:00', 'Post Title 10', 'publish', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (11, 2, '2026-05-12 12:00:00', 'Post Title 11', 'publish', 'post', 2);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (12, 3, '2026-05-13 12:00:00', 'Post Title 12', 'draft', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (13, 4, '2026-05-14 12:00:00', 'Post Title 13', 'publish', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (14, 5, '2026-05-15 12:00:00', 'Post Title 14', 'publish', 'page', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (15, 1, '2026-05-16 12:00:00', 'Post Title 15', 'draft', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (16, 2, '2026-05-17 12:00:00', 'Post Title 16', 'publish', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (17, 3, '2026-05-18 12:00:00', 'Post Title 17', 'publish', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (18, 4, '2026-05-19 12:00:00', 'Post Title 18', 'draft', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (19, 5, '2026-05-20 12:00:00', 'Post Title 19', 'publish', 'post', 1);
INSERT INTO wordpress.wp_posts (id, post_author, post_date, post_title, post_status, post_type, comment_count) VALUES (20, 1, '2026-05-21 12:00:00', 'Post Title 20', 'publish', 'post', 1);
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (1, 2, 'commenter1', '2026-06-02 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (2, 3, 'commenter2', '2026-06-03 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (3, 4, 'commenter3', '2026-06-04 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (4, 5, 'commenter4', '2026-06-05 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (5, 6, 'commenter5', '2026-06-06 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (6, 7, 'commenter6', '2026-06-07 15:00:00', '0');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (7, 8, 'commenter0', '2026-06-08 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (8, 9, 'commenter1', '2026-06-09 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (9, 10, 'commenter2', '2026-06-10 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (10, 11, 'commenter3', '2026-06-11 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (11, 12, 'commenter4', '2026-06-12 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (12, 13, 'commenter5', '2026-06-13 15:00:00', '0');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (13, 14, 'commenter6', '2026-06-14 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (14, 15, 'commenter0', '2026-06-15 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (15, 16, 'commenter1', '2026-06-16 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (16, 17, 'commenter2', '2026-06-17 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (17, 18, 'commenter3', '2026-06-18 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (18, 19, 'commenter4', '2026-06-19 15:00:00', '0');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (19, 20, 'commenter5', '2026-06-20 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (20, 1, 'commenter6', '2026-06-21 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (21, 2, 'commenter0', '2026-06-22 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (22, 3, 'commenter1', '2026-06-23 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (23, 4, 'commenter2', '2026-06-24 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (24, 5, 'commenter3', '2026-06-25 15:00:00', '0');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (25, 6, 'commenter4', '2026-06-26 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (26, 7, 'commenter5', '2026-06-27 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (27, 8, 'commenter6', '2026-06-28 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (28, 9, 'commenter0', '2026-06-01 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (29, 10, 'commenter1', '2026-06-02 15:00:00', '1');
INSERT INTO wordpress.wp_comments (comment_id, comment_post_id, comment_author, comment_date, comment_approved) VALUES (30, 11, 'commenter2', '2026-06-03 15:00:00', '0');
INSERT INTO wordpress.wp_terms (term_id, name, slug) VALUES (1, 'News', 'news');
INSERT INTO wordpress.wp_terms (term_id, name, slug) VALUES (2, 'Tech', 'tech');
INSERT INTO wordpress.wp_terms (term_id, name, slug) VALUES (3, 'Life', 'life');
INSERT INTO wordpress.wp_terms (term_id, name, slug) VALUES (4, 'golang', 'golang');
INSERT INTO wordpress.wp_terms (term_id, name, slug) VALUES (5, 'database', 'database');
INSERT INTO wordpress.wp_terms (term_id, name, slug) VALUES (6, 'ai', 'ai');
INSERT INTO wordpress.wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy) VALUES (1, 1, 'category');
INSERT INTO wordpress.wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy) VALUES (2, 2, 'category');
INSERT INTO wordpress.wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy) VALUES (3, 3, 'category');
INSERT INTO wordpress.wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy) VALUES (4, 4, 'post_tag');
INSERT INTO wordpress.wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy) VALUES (5, 5, 'post_tag');
INSERT INTO wordpress.wp_term_taxonomy (term_taxonomy_id, term_id, taxonomy) VALUES (6, 6, 'post_tag');
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (1, 2);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (2, 3);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (3, 4);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (4, 5);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (5, 6);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (6, 1);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (7, 2);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (8, 3);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (9, 4);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (10, 5);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (11, 6);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (12, 1);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (13, 2);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (14, 3);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (15, 4);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (16, 5);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (17, 6);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (18, 1);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (19, 2);
INSERT INTO wordpress.wp_term_relationships (object_id, term_taxonomy_id) VALUES (20, 3);
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (1, 1, 'views', '113');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (2, 2, 'views', '126');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (3, 3, 'views', '139');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (4, 4, 'views', '152');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (5, 5, 'views', '165');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (6, 6, 'views', '178');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (7, 7, 'views', '191');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (8, 8, 'views', '204');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (9, 9, 'views', '217');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (10, 10, 'views', '230');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (11, 11, 'views', '243');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (12, 12, 'views', '256');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (13, 13, 'views', '269');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (14, 14, 'views', '282');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (15, 15, 'views', '295');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (16, 16, 'views', '308');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (17, 17, 'views', '321');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (18, 18, 'views', '334');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (19, 19, 'views', '347');
INSERT INTO wordpress.wp_postmeta (meta_id, post_id, meta_key, meta_value) VALUES (20, 20, 'views', '360');
INSERT INTO wordpress.wp_options (option_id, option_name, option_value) VALUES (1, 'blogname', 'jamypg blog');
INSERT INTO wordpress.wp_options (option_id, option_name, option_value) VALUES (2, 'blogdescription', 'text2sql test blog');
INSERT INTO wordpress.wp_options (option_id, option_name, option_value) VALUES (3, 'posts_per_page', '10');
INSERT INTO wordpress.wp_options (option_id, option_name, option_value) VALUES (4, 'timezone_string', 'Asia/Seoul');
INSERT INTO wordpress.wp_options (option_id, option_name, option_value) VALUES (5, 'template', 'twentytwentysix');
GRANT USAGE ON SCHEMA wordpress TO jamypg_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA wordpress TO jamypg_ro;
